apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:    # service's own label, that could be used to select service
    app: redis  
    role: master
    tier: backend
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:  #specify the containers that this service will manage; and 3 labels must match the pods' labels
    app: redis
    role: master
    tier: backend
