apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
  labels:
    app: redis
spec:
  selector:  #specify the containers that this deployment will manage; and 3 labels must match the pods' labels
    matchLabels: # match labels on line 16, why is this not default? Are you going to create orphan, unmanaged pods?
      app: redis
      role: master
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:  # add labels to pods
        app: redis
        role: master
        tier: backend
    spec:
      containers:
      - name: master
        image: k8s.gcr.io/redis:e2e 
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 250m
            memory: 1024Mi
        ports:
        - containerPort: 6379
