# This is a basic workflow to help you started with Actions

name: Pipeline
# Controls when the action will run.
on:
 # Triggers the workflow on push or pull request events but only for the main branch and specific file and paths
 push:
   branches: [ main ]
   paths:
    - Chapter15/**
    - .github/workflows/pipeline.yaml  
# Allows you to run this workflow manually from the Actions tab
workflow_dispatch:
